### ISSUE TITLE
Its broken.

### ISSUE THREAD

**Issue by sdesalas** [kurankat/kis2kml#11]
I'm uploading to google maps and nothing works.  Pah! 😛 

Can you make my website for me? And my friends website too?

**Comment by kurankat** [comment]
Como lo sabes?
;-)

**Comment by kurankat** [comment]
Did it really not work? 
Which bit?

**Comment by sdesalas** [comment]
Na just kidding 😆

**Comment by sdesalas** [comment]
Still broke... :(

Can you fix my PC? The cup holder is not working anymore.
